### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Cidana-Developers** [Cidana-Developers/UnitTests-Task-manager#35]
Here are some todo items we should do, please feel free to comments:
- [x] Run coverage test and check if there is any assembly functions is tested. They may add some new assembly functions.
- [x] Check the buffer alignment and the function.
- [x] Check file name and assure the name is consistent. Like CamelCase instead of snake_case.
- [x] 10bit format support 
- [x] Merge Edmond's long-time test and multiple instance test;
- [x] Review the test code and obtain the detail of the coding tools.
- [x] Prepare a final e2e test document based on Emma's document.
- [x] Make our test work for encoder development, like executing regression test.
- [x] Support different color space (400, 422, 444)

**Comment by Cidana-Emma** [comment]
done
