### ISSUE TITLE
[SVT-AV1 UnitTests] Coveralls Support

### ISSUE THREAD

**Issue by edmond-zhu** [Cidana-Developers/UnitTests-Task-manager#61]
1. Coveralls support in Jenkins
- [x] demo for unit tests coverage
- [ ] Jenkins add super link to coveralls for short cut

2. Coveralls support in Travis (timeout limitation)
- [x] reduce test loop in unit tests
- [x] disable speed tests
- [x] filter some long time tests
- [x] multiple threads optimization

3. Coveralls not found in Travis Linux
- [x] fix Coveralls in Travis Linux

4. Coveralls fixing in Travis MacOS
- [ ] fix illegal instruction issue

**Comment by edmond-zhu** [comment]
Demo for Coveralls integration in Jenkins is ready [https://coveralls.io/github/edmond-zhu/coveralls_test](url)

**TODO: Jenkins add super link to coveralls after coverage test report as :**
~~~
22:20:52 
22:20:56 {u'url': u'https://coveralls.io/jobs/57402369', u'message': u'Job ##1.1'}
22:21:02 Run condition [Always] enabling perform for step [[Publish Cobertura Coverage Report]]
22:21:02 [Cobertura] Publishing Cobertura coverage report...
22:21:02 
22:21:02 [Cobertura] Publishing Cobertura coverage results...
22:21:02 
22:21:03 [Cobertura] Cobertura coverage report found.
22:21:03 
22:21:06 Setting status of 071d90a3ce90559324116095dac77a154c90da91 to SUCCESS with url http://jenkins.cidanash.com:8082/job/SVTAV1-Coverage/174/ and message: 'Succeeded
22:21:06 coverage_test @./generate_report.sh
22:21:06  '
22:21:06 Using context:  OpenVisualCloud/Coverage-Test
22:21:07 Finished: SUCCESS
~~~

**Comment by edmond-zhu** [comment]
CPU info of Travis Virtual Machine
~~~
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU
stepping	: 7
microcode	: 0x1
cpu MHz		: 2800.246
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa itlb_multihit
bogomips	: 5600.49
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU
stepping	: 7
microcode	: 0x1
cpu MHz		: 2800.246
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa itlb_multihit
bogomips	: 5600.49
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
~~~

**Comment by edmond-zhu** [comment]
Travis timeout limitation errors:
1. The job exceeded the maximum time limit for jobs, and has been terminated. (about 50 minutes)
2. No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by edmond-zhu** [comment]
Task2 result after 
- [x] reduce test loop in unit tests
- [x] disable speed tests
~~~
[==========] 29073 tests from 138 test cases ran. (14152080 ms total)
~~~

Still costs about 236 minutes in single thread running _SvtAv1UnitTests_

**[DONE]: disable some long time test cases**
- [x] filter some long time tests

**Comment by edmond-zhu** [comment]
Test result on Intel i-7 8750H @4GHz single thread

Test Case | Running Time
-- | --
LOOPSAD/sad_LoopTest | 3716227
HMESAD/sad_LoopTest | 2214982
EbRestorationPick_avx2 | 1431346
Cdef/CDEFBlockTest | 1346854
ConvolveTest2D/AV1HbdJntConvolve2DTest | 878943
BlendA64Mask1DTestHBD | 488241
BlendA64Mask1DTest8B | 480472
C/AV1WarpFilterTest | 450115
SSE4_1/AV1HighbdWarpFilterTest | 371923
AVX2/AV1WarpFilterTest | 305547
BlendA64MaskTest8B | 284894
ConvolveTest2D/AV1LbdJntConvolve2DTest | 282418
Av1KMeansDim/Av1KMeansDim | 217491
BlendA64MaskTestHBD_d16 | 146081
BlendA64MaskTestHBD | 145228
SelfGuidedToolsTest | 132650
TX/InvTxfm2dAsmTest | 108061
TX_AVX2/InvTxfm2dAsmTest | 107621
BlendA64MaskTest8B_d16 | 84609
SSE2/EncodeTxbTest | 63735
OBMC/OBMCVarianceTest | 55778
OBMC/OBMCSubPixelVarianceTest | 55573
WedgeUtilTest | 54517
OBMC/OBMCsad_Test | 54297
ConvolveTest2D/AV1HbdSrConvolve2DTest | 50218
AV1/AV1WienerConvolveHbdTest | 42925
BLEND/HbdCompBlendD16Test | 40510
BLEND/HbdCompBlendTest | 37806
PalleteMode/KMeansTest | 35593
AV1/PsnrCalcHbdTest | 28446
BLEND/LbdCompBlendTest | 24572
TX/AV1FwdTxfm2dTest | 24316
TemporalFilter/TemporalFilterTest | 23283
AV1/AV1WienerConvolveLbdTest | 22574
Cdef/CDEFFindDirTest | 20955
BLEND/HbdCompBlendHMaskTest | 17463
EIGHTSAD/GetEightsad_Test | 17431
BLEND/HbdCompBlendVMaskTest | 16949
AVCMCPPU/AVCStyleMcpPUTest | 16293
ConvolveTest2D/AV1LbdSrConvolve2DTest | 16227
ConvolveTestY/AV1HbdJntConvolve2DTest | 13283
ConvolveTestX/AV1HbdJntConvolve2DTest | 13279
BLEND/LbdCompBlendD16Test | 12533
SSDAvg/SSDAvgTest | 12253
SAD/SADTest | 11944
SAD/SADAvgTest | 11923
SAD/SADTestSubSample | 11917
UpsampleTestLBD | 11342
AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest | 10039
GlobalMotion/RansacIntTest | 8395
GlobalMotion/RansacDoubleTest | 8103
intrapred/LowbdIntraPredTest | 7558
IntraFilterEdgeTestLowbd | 7417
IntraFilterEdgeTestHighbd | 7380
intrapred/HighbdIntraPredTest | 6868
CdefToolTest | 6278
SSE2/HbdLoopFilterTest | 6124
FFT/FFT2DTest | 5835
BLEND/LbdCompBlendVMaskTest | 5680
BLEND/LbdCompBlendHMaskTest | 5663
ConvolveTestX/AV1LbdJntConvolve2DTest | 4230
ConvolveTestY/AV1LbdJntConvolve2DTest | 4201
Variance/VarianceTest | 3637
AVX2/AV1HighbdSelfguidedFilterTest | 3453
ColorCountHbdTest | 3389
RST/PixelProjErrorHbdTest | 2398
RST/PixelProjErrorLbdTest | 2397
AVX2/AV1FrameErrorTest | 2382
IFFT/IFFT2DTest | 2065
SSE2/LbdLoopFilterTest | 1759
Quant/QuantizeBTest | 1744
SAD/SADTestSubSample16bit | 1649
AV1/FilterIntraPredTest | 1479
ALLSAD/Allsad_CalculationTest | 1394
EXTSAD/Extsad_CalculationTest | 1390
CALSAD/sad_CalculationTest | 1389
AVX2/AV1SelfguidedFilterTest | 1139
CompUtilTest/BuildCompDiffwtdMaskTest | 1128
TX/FwdTxfm2dAsmTest | 1103
ColorCountLbdTest | 1059
TX/AV1FwdTxfm1dTest | 959
Variance/HbdVarianceTest | 885
ConvolveTestY/AV1HbdSrConvolve2DTest | 876
ConvolveTestX/AV1HbdSrConvolve2DTest | 871
FullDistortionKernel16FuncTest/FullDistortionKernel16BitsFuncTest | 694
AV1/PsnrCalcLbdTest | 593
AVCMCPSearchRegionHelper/AVCStyleMcpSearchRegionTestHelper | 492
AVCMCPPU_HELPER/AVCStyleMcpPUTestHelper | 469
AVX2/CflSubAvgTest | 465
HighbdDrZ2Test | 365
LowbdDrZ2Test | 353
AVX2_COPY/AV1HbdJntConvolve2DTest | 353
UNPACKAVG/UnPackAvgTest | 350
ConvolveTestY/AV1LbdSrConvolve2DTest | 287
ConvolveTestX/AV1LbdSrConvolve2DTest | 284
BitstreamWriterTest | 277
HighbdDrZ3Test | 249
LowbdDrZ3Test | 246
HighbdDrZ1Test | 242
SpatialKernelFunc/SpatialFullDistortionKernelFuncTest | 241
LowbdDrZ1Test | 240
UNPACK/UnPackTest | 224
ComputeMeanTest | 215
ConvolveTestCopy/AV1HbdSrConvolve2DTest | 162
TX/AV1InvTxfm1dTest | 141
DenoiseModelRunTest | 123
Variance/HbdSquareVarianceTest | 116
PACK2D/Pack2dTest | 113
ConvolveTestCOPY/AV1LbdJntConvolve2DTest | 113
ExtractFilterTest | 108
SSE4_1/BuildCompDiffwtdMaskD16Test | 99
Entropy/EncodeTxbInitLevelTest | 80
ResidualUtil/ResidualKernelTest | 72
SpatialFunc/SpatialFullDistortionFuncTest | 54
ConvolveTestCopy/AV1LbdSrConvolve2DTest | 54
PictureOperator/PictureOperatorTest | 47
MotionEstimation_avx2 | 34
HBDVarianceTest/HBDVarianceTest | 30
AV1CornerMatchTest/AV1CornerMatchTest | 26
AVX2/SpatialFullDistortionTest | 19
PACK/PackTest | 14
Variance/MseTestHighbd | 14
Variance/MseTest | 12
LbdCflPredMatchTest | 10
HbdCflPredMatchTest | 10
Compute8x8SatdTest | 9
Entropy_BitstreamWriter | 5
PACKMSB/PackMsbTest | 5
AddFilmGrainTest | 3
Variance/SumSquareTest | 2
AdaptiveScanTest | 1
AV1/DvValiationTest | 1
FilmGrain | 0
TransposeTest | 0
NNPRED/NNPredTest | 0
InitializeBuffer32/InitializeBuffer32 | 0
TRANSPOSE/Transpose32Bit8x8Test | 0
TRANSPOSE/Transpose64BitTest | 0

**Comment by edmond-zhu** [comment]
TO disable test cases:
- \*sad_LoopTest\*
- \*EbRestorationPick\*
- \*JntConvolve\*
- \*WarpFilterTest\*
- \*BlendA64Mask\*
- \*Av1KMeansDim\*

**This number after optimization is about 32.02% in lines:**
[https://coveralls.io/jobs/57553240](url)

- [x] multiple threads optimization
Optimized from [single thread](https://travis-ci.com/Cidana-Developers/SVT-AV1/jobs/273413929) (31 min 36 sec) to [dual threads](https://travis-ci.com/Cidana-Developers/SVT-AV1/jobs/273430682) (29 min 34 sec)

**Comment by edmond-zhu** [comment]
Issue found in [Travis Linux](https://travis-ci.com/Cidana-Developers/SVT-AV1/jobs/273362325):
~~~
Collecting cpp-coveralls
  Downloading https://files.pythonhosted.org/packages/93/92/1d07234b151791c173a299c4007ee050cddda43b638452c47f25880db0d8/cpp-coveralls-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-psd_m9ca/cpp-coveralls/
~~~
~~~
$ if [ $CC = "clang" ] && [ $TRAVIS_OS_NAME = linux ]; then
    GCOV_FILE=llvm-cov GCOV_OPTIONS='gcov -pl'
  else
    GCOV_FILE=gcov GCOV_OPTIONS='\-lp'
  fi
  coveralls --root $TRAVIS_BUILD_DIR -i Source -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*third_party.*" -E ".*test/FilmGrainTest.cc" -E ".*ffmpeg.*" --gcov $GCOV_FILE --gcov-options "$GCOV_OPTIONS"
Command 'coveralls' not found, but can be installed with:
apt install ruby-coveralls
Please ask your administrator.
~~~

**Fixed with patch:**
~~~
pip3 install --upgrade setuptools
python3 -m pip install --upgrade pip
pip3 install --user cpp-coveralls
~~~

**Comment by edmond-zhu** [comment]
Issue found in [Travis MacOS](https://travis-ci.com/Cidana-Developers/SVT-AV1/jobs/273375121)
~~~
[----------] 4 tests from CdefToolTest
[ RUN      ] CdefToolTest.CopyRectMatchTest
[       OK ] CdefToolTest.CopyRectMatchTest (12 ms)
[ RUN      ] CdefToolTest.ComputeCdefDistMatchTest
/Users/travis/.travis/functions: line 111:  9966 Illegal instruction: 4  SvtAv1UnitTests --gtest_filter=*-*sad_LoopTest*:*EbRestorationPick*:*JntConvolve*:*AV1WarpFilterTest*:*AV1HighbdWarpFilter*:*BlendA64Mask*:*CDEFBlockTest*:*Av1KMeansDim*:*InvTxfm2dAsmTest *
~~~

**Comment by Cidana-Emma** [comment]
Provided the overall coverage script to Netflix.
