### ISSUE TITLE
[SVT-AV1 UnitTests] Failure Test Case Tracking

### ISSUE THREAD

**Issue by edmond-zhu** [Cidana-Developers/UnitTests-Task-manager#65]
This task is a tracking board for failed test cases in unit tests.

@Richard-li Please list and update the remaining failure test cases here:

**Comment by Richard-li** [comment]
Failing test case in unit test <Commits on Jan. 6th, 2020>
**Classification:**
- [ ] FFT/FFT2DTest

- [ ] IFFT/IFFT2DTest

- [ ] AVX2_COPY/AV1HbdJntConvolve2DTest

- [ ] ConvolveTest2D/AV1HbdJntConvolve2DTest

- [ ] ConvolveTestX/AV1HbdJntConvolve2DTest

- [ ] ConvolveTestY/AV1HbdJntConvolve2DTest

- [ ] AV1/AV1WienerConvolveHbdTest

**Failure info detail:**
[  FAILED  ] 58 tests, listed below:
[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/3, where GetParam() = (00007FF6DA719050, 00007FF6DA892A70, 00007FF6DA71A2E0, 16)
[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/4, where GetParam() = (00007FF6DA71A260, 00007FF6DA894110, 00007FF6DA71BDC0, 32)
[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/8, where GetParam() = (00007FF6DA719050, 00007FF6DA892A70, 00007FF6DA894670, 16)
[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/9, where GetParam() = (00007FF6DA71A260, 00007FF6DA894110, 00007FF6DA8965B0, 32)
[  FAILED  ] IFFT/IFFT2DTest.run_ifft_accuracy_check/2, where GetParam() = (00007FF6DA71BE10, 00007FF6DA896650, 8)
[  FAILED  ] IFFT/IFFT2DTest.run_ifft_accuracy_check/3, where GetParam() = (00007FF6DA71A2E0, 00007FF6DA894670, 16)
[  FAILED  ] IFFT/IFFT2DTest.run_ifft_accuracy_check/4, where GetParam() = (00007FF6DA71BDC0, 00007FF6DA8965B0, 32)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/0, where GetParam() = (8, 0, 0, 0, 0)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/1, where GetParam() = (8, 0, 0, 0, 1)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/16, where GetParam() = (8, 0, 0, 0, 16)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/22, where GetParam() = (10, 0, 0, 0, 0)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/23, where GetParam() = (10, 0, 0, 0, 1)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/38, where GetParam() = (10, 0, 0, 0, 16)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/44, where GetParam() = (12, 0, 0, 0, 0)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/45, where GetParam() = (12, 0, 0, 0, 1)
[  FAILED  ] AVX2_COPY/AV1HbdJntConvolve2DTest.MatchTest/60, where GetParam() = (12, 0, 0, 0, 16)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/0, where GetParam() = (8, 1, 1, 0, 0)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/1, where GetParam() = (8, 1, 1, 0, 1)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/16, where GetParam() = (8, 1, 1, 0, 16)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/22, where GetParam() = (10, 1, 1, 0, 0)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/23, where GetParam() = (10, 1, 1, 0, 1)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/38, where GetParam() = (10, 1, 1, 0, 16)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/44, where GetParam() = (12, 1, 1, 0, 0)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/45, where GetParam() = (12, 1, 1, 0, 1)
[  FAILED  ] ConvolveTest2D/AV1HbdJntConvolve2DTest.MatchTest/60, where GetParam() = (12, 1, 1, 0, 16)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/0, where GetParam() = (8, 1, 0, 0, 0)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/1, where GetParam() = (8, 1, 0, 0, 1)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/16, where GetParam() = (8, 1, 0, 0, 16)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/22, where GetParam() = (10, 1, 0, 0, 0)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/23, where GetParam() = (10, 1, 0, 0, 1)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/38, where GetParam() = (10, 1, 0, 0, 16)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/44, where GetParam() = (12, 1, 0, 0, 0)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/45, where GetParam() = (12, 1, 0, 0, 1)
[  FAILED  ] ConvolveTestX/AV1HbdJntConvolve2DTest.MatchTest/60, where GetParam() = (12, 1, 0, 0, 16)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/0, where GetParam() = (8, 0, 1, 0, 0)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/1, where GetParam() = (8, 0, 1, 0, 1)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/16, where GetParam() = (8, 0, 1, 0, 16)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/22, where GetParam() = (10, 0, 1, 0, 0)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/23, where GetParam() = (10, 0, 1, 0, 1)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/38, where GetParam() = (10, 0, 1, 0, 16)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/44, where GetParam() = (12, 0, 1, 0, 0)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/45, where GetParam() = (12, 0, 1, 0, 1)
[  FAILED  ] ConvolveTestY/AV1HbdJntConvolve2DTest.MatchTest/60, where GetParam() = (12, 0, 1, 0, 16)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/3, where GetParam() = ((88, 88), 00007FF6DA782D60, 8)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/4, where GetParam() = ((88, 88), 00007FF6DA782D60, 10)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/5, where GetParam() = ((88, 88), 00007FF6DA782D60, 12)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/9, where GetParam() = ((72, 72), 00007FF6DA782D60, 8)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/10, where GetParam() = ((72, 72), 00007FF6DA782D60, 10)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/11, where GetParam() = ((72, 72), 00007FF6DA782D60, 12)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/15, where GetParam() = ((56, 56), 00007FF6DA782D60, 8)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/16, where GetParam() = ((56, 56), 00007FF6DA782D60, 10)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/17, where GetParam() = ((56, 56), 00007FF6DA782D60, 12)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/24, where GetParam() = ((24, 24), 00007FF6DA782D60, 8)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/25, where GetParam() = ((24, 24), 00007FF6DA782D60, 10)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/26, where GetParam() = ((24, 24), 00007FF6DA782D60, 12)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/30, where GetParam() = ((8, 8), 00007FF6DA782D60, 8)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/31, where GetParam() = ((8, 8), 00007FF6DA782D60, 10)
[  FAILED  ] AV1/AV1WienerConvolveHbdTest.random_test/32, where GetParam() = ((8, 8), 00007FF6DA782D60, 12)

**Comment by Cidana-Emma** [comment]
Test failures in AV1HbdJntConvolve2DTest and AV1WienerConvolveHbdTest have been fixed by PR#954 in SVT-AV1 GitHub.

**Comment by Cidana-Emma** [comment]
PR#954 has been merged, so close this issue
